FlyBuy SDK Module Separation into each package
BILDIT-Platform/react-native-bildit-flybuy pull request #88
Opened 2024-08-09 12:53 UTC by addingama

2024-08-09 14:21 UTC, garriott-bildit approved these changes

2024-08-22 13:17 UTC, botnerd requested changes
Please move the `FlyBuyCore` methods into groups (`Customer`, `Sites`, and `Orders`) like they were prior to the modularization. Everything else looks good.

2024-08-22 13:17 UTC, botnerd commented on docusaurus-docs/docs/Migration.md
> +All function names are not modified, you just need to change `FlyBuy.<MODULENAME>` to one of the above import alias.
```suggestion
Version 2.20.x and higher move to a modularized architecture where the react native modules mirror the modules in the native SDK. This allows app to pull in only the modules they need. To migrate to the new architecture, please perform the following steps.

## package.json dependencies

Remove `"react-native-bildit-flybuy"` from package.json dependencies, and include the modules that are needed as follows. Core is required. Other modules depend on the features your app is using.

```json
  "dependencies": {
    "react-native-bildit-flybuy-core": "2.20.4",
    "react-native-bildit-flybuy-livestatus": "2.20.4",
    "react-native-bildit-flybuy-notify": "2.20.4",
    "react-native-bildit-flybuy-pickup": "2.20.4",
    "react-native-bildit-flybuy-presence": "2.20.4"
  }
```

## Update code

Most of the code remains the same; however, new imports are needed and the main core class has changed.

Version 2.3.x

```js
  import FlyBuy from 'react-native-bildit-flybuy';

  FlyBuy.Core.Orders.fetchOrders()
      .then(orders => console.tron.log('orders', orders))
      .catch(err => console.tron.log(err));
```

Version 2.20.x

```js
  import * as FlyBuyCore from 'react-native-bildit-flybuy-core';

  FlyBuyCore.Orders.fetchOrders()
      .then(orders => console.tron.log('orders', orders))
      .catch(err => console.tron.log(err));
```

Import format for other modules


```js
  import * as FlyBuyCore from 'react-native-bildit-flybuy-core';
  import * as FlyBuyPickup from 'react-native-bildit-flybuy-pickup';
  import * as FlyBuyNotify from 'react-native-bildit-flybuy-notify';
  import * as FlyBuyPresence from 'react-native-bildit-flybuy-presence';
  import * as FlyBuyLiveStatus from 'react-native-bildit-flybuy-livestatus';
```

All function names are not modified, you just need to change `FlyBuy.<MODULENAME>` to one of the above import alias.
```

2024-08-22 13:17 UTC, botnerd commented on mono/packages/core/ios/RnFlybuyCore.h
> +    withRejecter:(RCTPromiseRejectBlock)reject;
All of these methods belong under `FlyBuyCore.Customer`

2024-08-22 13:17 UTC, botnerd commented on mono/packages/core/ios/RnFlybuyCore.h
> +    withRejecter:(RCTPromiseRejectBlock)reject;
All of these methods belong under `FlyBuyCore.Sites`

2024-08-22 13:17 UTC, botnerd commented on mono/packages/core/ios/RnFlybuyCore.h
> +    withRejecter:(RCTPromiseRejectBlock)reject;
All of these methods belong under `FlyBuyCore.Orders`

2024-08-26 13:38 UTC, botnerd approved these changes
Everything looks good to me!

2024-08-30 13:51 UTC, merged